name: Compatibility

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  latest:
    name: Latest dependency versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - run: uv python install 3.13
      - run: uv sync --group dev --upgrade
      - run: uv run pytest -v

  lowest:
    name: Lowest declared bounds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - run: uv python install 3.10
      - run: uv sync --group dev --resolution lowest-direct
      - run: uv run pytest -v
